### ISSUE TITLE
Redactor randomly deletes all links in a block, or in the rest of the field

### ISSUE THREAD

**Issue by nicbou** [craftcms/redactor#331]
### Description

In Firefox and Chrome, inserting a link will randomly delete all surrounding links. Once in a while, I don't notice it happening, and I have to manually reinsert dozens of references and external links on the page. It's infuriating, since it can erase hours of work.

This issue is very common (~60% of the time), and it has been there since I started using Craft. I wanted to report it to Redactor, but they have no sort of community forum.

### Steps to reproduce

1. In a long article, double-click a word to select it
2. Insert a link (Cmd + K). It happens more often with <em> text
2. When you save the link, watch for surrounding links being removed, and appearing as normal text.

https://user-images.githubusercontent.com/88917/122943603-73111380-d377-11eb-9a54-835f8aaf3d3e.mov

### Additional info

- Craft version: all versions from the last 4 years, including a fully updated Craft setup.
- Browser: all Chrome and Firefox versions from the last 4 years

**Comment by nicbou** [comment]
First mentioned here 4 years ago: https://github.com/craftcms/cms/issues/2158

**Comment by croxton** [comment]
Long shot, but does this bug happen after using Live Preview? I'm wondering if this pr for a long standing JS error would fix other odd issues like this too:
https://github.com/craftcms/redactor/pull/329

**Comment by nicbou** [comment]
I never use live preview, so that is very unlikely. The example above happened on a freshly loaded page.

**Comment by croxton** [comment]
I've had editors report this bug but I've never been able to reproduce it. My editors say it happens randomly but there must be a cause. Would you mind pasting the exact html you are editing above and the Redactor config?

**Comment by nicbou** [comment]
It happens _very_ frequently. The problem is completely random, but the easiest way to reproduce it is to select a word, italicise it (Cmd + I), and link to it (Cmd + K). Redactor seems to hate this.

Uploading Screen Recording 2021-06-28 at 12.06.29.mov…

For example, select the word "their" in the HTML below, then Cmd + I, then Cmd + K. When you save the link, all links before that word get deleted.

```
<h2>Tipping at the restaurant</h2>
<p>Germans usually tip their waiters<sup><a href="https://en.wikipedia.org/wiki/Gratuity#Germany">1</a></sup>. Tipping is not mandatory, but it's common<sup><a href="https://en.wikipedia.org/wiki/Gratuity#Germany">1</a></sup>. German waiters do not depend on tips to survive, but it's a big part of their income<sup><a href="https://www.reddit.com/r/germany/comments/b48xti/how_does_one_tip_in_berlin/ej56dbp/">1</a>, <a href="https://www.reddit.com/r/germany/comments/2wptvp/do_you_guys_give_tips/cotaw6a/">2</a></sup>.</p>
```

Redactor and field configs:

```
{
	"buttons": ["html","format","bold","italic","lists","link","file","image","video","horizontalrule"],
	"plugins": ["inlinestyle", "fullscreen", "table", "video", "pagebreak", "widget"],
	"imageResizable": true,
	"imagePosition": true
}
```

```
contentColumnType: mediumtext
fieldGroup: 24164084-1fbe-4cb3-8263-5c3215381e7d
handle: body
instructions: ''
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: mediumtext
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Advanced.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
```

This is a huge problem for me, especially with auto-saving drafts. It can undo large swathes of my work, and if I don't immediately notice, I have to manually fix everything. I have wasted hours on this bug this years.
