### ISSUE TITLE
Fullscreen in element slide-outs is broken

### ISSUE THREAD

**Issue by croxton** [craftcms/redactor#445]
### Description
When using the fullscreen button in a Redactor field in a slide-out, the fullscreen editor is hidden behind the slide-out panel.

### Suggested Fix:
Change the `z-index` of the Redactor container when it is in full-screen mode inside a slide-out:
```css
/* Fix full screen in slide-outs */
.redactor-element-editor-open .redactor-box.redactor-box-fullscreen {
    z-index: 1000 !important; /* was 100 */
}
```
